
universe       = vanilla
executable     = TOFAllscan/LiHMu_3172_tof_lim28.7147513286_u28.9147513286.sh
output         = /home/ppe/j/jnugent/workarea/Unfolding/TOFScan/LiHMu_3172_tof_lim28.7147513286_u28.9147513286.out
error          = /home/ppe/j/jnugent/workarea/Unfolding/TOFScan/LiHMu_3172_tof_lim28.7147513286_u28.9147513286.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
