
universe       = vanilla
executable     = TOFAllscan/LiHMu_3200_tof_lim29.7365596446_u29.9365596446.sh
output         = /home/ppe/j/jnugent/workarea/Unfolding/TOFScan/LiHMu_3200_tof_lim29.7365596446_u29.9365596446.out
error          = /home/ppe/j/jnugent/workarea/Unfolding/TOFScan/LiHMu_3200_tof_lim29.7365596446_u29.9365596446.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
