
universe       = vanilla
executable     = TOFAllscan/LiHMu_3200_tof_lim27.1365596446_u27.3365596446.sh
output         = /home/ppe/j/jnugent/workarea/Unfolding/TOFScan/LiHMu_3200_tof_lim27.1365596446_u27.3365596446.out
error          = /home/ppe/j/jnugent/workarea/Unfolding/TOFScan/LiHMu_3200_tof_lim27.1365596446_u27.3365596446.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
