
universe       = vanilla
executable     = accp_rad_0/LiHMu_3200_140.sh
output         = /data/neutrino03/jnugent/Unfolding/scanradial/accp_rad_0/LiHMu_3200_140.out
error          = /data/neutrino03/jnugent/Unfolding/scanradial/accp_rad_0/LiHMu_3200_140.err
log            = /data/neutrino03/jnugent/Unfolding/scanradial/accp_rad_0/LiHMu_3200_140.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 12 GB

queue
