
universe       = vanilla
executable     = accp_rad_0/LiHMu_3200_40.sh
output         = /data/neutrino03/jnugent/Unfolding/scanradial/accp_rad_0/LiHMu_3200_40.out
error          = /data/neutrino03/jnugent/Unfolding/scanradial/accp_rad_0/LiHMu_3200_40.err
log            = /data/neutrino03/jnugent/Unfolding/scanradial/accp_rad_0/LiHMu_3200_40.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 12 GB

queue
