
universe       = vanilla
executable     = LiHMu_3200_tof_lim27.1643870826_u27.3643870826.sh
output         = /data/neutrino03/jnugent/Unfolding/USDS_mom_cor/LiHMu_3200_tof_lim27.1643870826_u27.3643870826.out
error          = /data/neutrino03/jnugent/Unfolding/USDS_mom_cor/LiHMu_3200_tof_lim27.1643870826_u27.3643870826.err
log            = /data/neutrino03/jnugent/Unfolding/USDS_mom_cor/LiHMu_3200_tof_lim27.1643870826_u27.3643870826.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 6 GB

queue
