
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0019999999999999844.sh
output         = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_-0.0019999999999999844.out
error          = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_-0.0019999999999999844.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
