
universe       = vanilla
executable     = LiHMu_3240_tof_lim27.4570317938_u27.6570317938.sh
output         = /home/ppe/j/jnugent/workarea/Unfolding/TOFsys/LiHMu_3240_tof_lim27.4570317938_u27.6570317938.out
error          = /home/ppe/j/jnugent/workarea/Unfolding/TOFsys/LiHMu_3240_tof_lim27.4570317938_u27.6570317938.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
