
universe       = vanilla
executable     = LiHMu_3172_tof_lim27.9374090796_u28.1374090796.sh
output         = /home/ppe/j/jnugent/workarea/Unfolding/TOFsys/LiHMu_3172_tof_lim27.9374090796_u28.1374090796.out
error          = /home/ppe/j/jnugent/workarea/Unfolding/TOFsys/LiHMu_3172_tof_lim27.9374090796_u28.1374090796.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
