
universe       = vanilla
executable     = effi_0/LiHMu_3200_15.sh
output         = /data/neutrino03/jnugent/Unfolding/effi_scan/effi_0/LiHMu_3200_15.out
error          = /data/neutrino03/jnugent/Unfolding/effi_scan/effi_0/LiHMu_3200_15.err
log            = /data/neutrino03/jnugent/Unfolding/effi_scan/effi_0/LiHMu_3200_15.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 50 GB

queue
