
cd /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan
. /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/local_env.sh
# /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3172_tof_lim28.1147513286_u28.3147513286MC.xml
# python CompCobbData.py TOFAllscan/LiHMu_3172_tof_lim28.1147513286_u28.3147513286MC.root TOFAllscan/LiHMu_3172_tof_lim28.1147513286_u28.3147513286_mod.root
/afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3172_tof_lim28.1147513286_u28.3147513286.xml
