
cd /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan
. /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/local_env.sh
# /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3200_tof_lim29.3365596446_u29.5365596446MC.xml
# python CompCobbData.py TOFAllscan/LiHMu_3200_tof_lim29.3365596446_u29.5365596446MC.root TOFAllscan/LiHMu_3200_tof_lim29.3365596446_u29.5365596446_mod.root
/afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3200_tof_lim29.3365596446_u29.5365596446.xml
