
cd /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan
. /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/local_env.sh
# /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3240_tof_lim27.7398395872_u27.9398395872MC.xml
# python CompCobbData400.py TOFAllscan/LiHMu_3240_tof_lim27.7398395872_u27.9398395872MC.root TOFAllscan/LiHMu_3240_tof_lim27.7398395872_u27.9398395872_mod.root
/afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3240_tof_lim27.7398395872_u27.9398395872.xml
