
cd /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan
. /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/local_env.sh
# /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3240_tof_lim28.1398395872_u28.3398395872MC.xml
# python CompCobbData400.py TOFAllscan/LiHMu_3240_tof_lim28.1398395872_u28.3398395872MC.root TOFAllscan/LiHMu_3240_tof_lim28.1398395872_u28.3398395872_mod.root
/afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3240_tof_lim28.1398395872_u28.3398395872.xml
