
cd /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan
. /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/local_env.sh
# /afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3200_tof_lim28.7365596446_u28.9365596446MC.xml
# python CompCobbData.py TOFAllscan/LiHMu_3200_tof_lim28.7365596446_u28.9365596446MC.root TOFAllscan/LiHMu_3200_tof_lim28.7365596446_u28.9365596446_mod.root
/afs/phas.gla.ac.uk/user/j/jnugent/workarea/Unfolding/TOFScan/../MCSUnfolding TOFAllscan/LiHMu_3200_tof_lim28.7365596446_u28.9365596446.xml
