#!/bin/bash

cp ../MClih172/LihMuon_03172.root MCLihMuon_03172.root 
cp ../MClih200/LihMuon_03200.root MCLihMuon_03200.root 
cp ../MClih240/LihMuon_03240.root MCLihMuon_03240.root 
cp ../lih240/LihMuon_03240.root LihMuon_03240.root 
cp ../lih200/LihMuon_03200.root LihMuon_03200.root 
cp ../lih172/LihMuon_03172.root LihMuon_03172.root
