
universe       = vanilla
executable     = LiHMu_3200_tof_lim29.4059285384_u29.6059285384.sh
output         = /home/ppe/j/jnugent/workarea/Unfolding/TOFsys/LiHMu_3200_tof_lim29.4059285384_u29.6059285384.out
error          = /home/ppe/j/jnugent/workarea/Unfolding/TOFsys/LiHMu_3200_tof_lim29.4059285384_u29.6059285384.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
