
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0012000000000000162.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0012000000000000162.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0012000000000000162.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0012000000000000162.log
requirements   = OpSysAndVer == "CentOS7"

queue
