
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-9.999999999999961e-05.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-9.999999999999961e-05.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-9.999999999999961e-05.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-9.999999999999961e-05.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
