
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0037000000000000236.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0037000000000000236.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0037000000000000236.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0037000000000000236.log
requirements   = OpSysAndVer == "CentOS7"

queue
