
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.002800000000000004.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002800000000000004.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002800000000000004.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002800000000000004.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
