
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0012000000000000066.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0012000000000000066.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0012000000000000066.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0012000000000000066.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
