
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0017000000000000175.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0017000000000000175.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0017000000000000175.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0017000000000000175.log
requirements   = OpSysAndVer == "CentOS7"

queue
