
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.001999999999999988.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001999999999999988.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001999999999999988.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001999999999999988.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
