
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0021000000000000185.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0021000000000000185.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0021000000000000185.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0021000000000000185.log
requirements   = OpSysAndVer == "CentOS7"

queue
