
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0039000000000000224.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0039000000000000224.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0039000000000000224.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0039000000000000224.log
requirements   = OpSysAndVer == "CentOS7"

queue
