
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0031000000000000203.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0031000000000000203.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0031000000000000203.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0031000000000000203.log
requirements   = OpSysAndVer == "CentOS7"

queue
