
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.003200000000000003.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003200000000000003.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003200000000000003.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003200000000000003.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
