
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.004300000000000023.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004300000000000023.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004300000000000023.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004300000000000023.log
requirements   = OpSysAndVer == "CentOS7"

queue
