
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0019999999999999922.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0019999999999999922.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0019999999999999922.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0019999999999999922.log
requirements   = OpSysAndVer == "CentOS7"

queue
