
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0023999999999999933.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0023999999999999933.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0023999999999999933.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0023999999999999933.log
requirements   = OpSysAndVer == "CentOS7"

queue
