
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0005999999999999903.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0005999999999999903.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0005999999999999903.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0005999999999999903.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
