
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.003000000000000021.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003000000000000021.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003000000000000021.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003000000000000021.log
requirements   = OpSysAndVer == "CentOS7"

queue
