
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.00020000000000001354.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00020000000000001354.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00020000000000001354.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00020000000000001354.log
requirements   = OpSysAndVer == "CentOS7"

queue
