
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.002699999999999994.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002699999999999994.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002699999999999994.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002699999999999994.log
requirements   = OpSysAndVer == "CentOS7"

queue
