
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0009.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0009.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0009.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0009.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
