
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0020999999999999925.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0020999999999999925.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0020999999999999925.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0020999999999999925.log
requirements   = OpSysAndVer == "CentOS7"

queue
