
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0016000000000000172.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0016000000000000172.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0016000000000000172.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0016000000000000172.log
requirements   = OpSysAndVer == "CentOS7"

queue
