
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0016999999999999914.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0016999999999999914.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0016999999999999914.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0016999999999999914.log
requirements   = OpSysAndVer == "CentOS7"

queue
