
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.001899999999999992.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001899999999999992.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001899999999999992.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001899999999999992.log
requirements   = OpSysAndVer == "CentOS7"

queue
