
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0035000000000000213.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0035000000000000213.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0035000000000000213.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0035000000000000213.log
requirements   = OpSysAndVer == "CentOS7"

queue
