
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0021999999999999876.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0021999999999999876.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0021999999999999876.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0021999999999999876.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
