
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0010999999999999899.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0010999999999999899.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0010999999999999899.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0010999999999999899.log
requirements   = OpSysAndVer == "CentOS7"

queue
