
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0022000000000000188.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0022000000000000188.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0022000000000000188.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0022000000000000188.log
requirements   = OpSysAndVer == "CentOS7"

queue
