
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0028000000000000204.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0028000000000000204.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0028000000000000204.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0028000000000000204.log
requirements   = OpSysAndVer == "CentOS7"

queue
