
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0009999999999999896.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0009999999999999896.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0009999999999999896.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0009999999999999896.log
requirements   = OpSysAndVer == "CentOS7"

queue
