
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-8.673617379884035e-18.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-8.673617379884035e-18.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-8.673617379884035e-18.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-8.673617379884035e-18.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
