
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.004900000000000027.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004900000000000027.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004900000000000027.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004900000000000027.log
requirements   = OpSysAndVer == "CentOS7"

queue
