
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0047000000000000245.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0047000000000000245.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0047000000000000245.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0047000000000000245.log
requirements   = OpSysAndVer == "CentOS7"

queue
