
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0044000000000000246.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0044000000000000246.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0044000000000000246.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0044000000000000246.log
requirements   = OpSysAndVer == "CentOS7"

queue
