
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0028999999999999946.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0028999999999999946.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0028999999999999946.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0028999999999999946.log
requirements   = OpSysAndVer == "CentOS7"

queue
