
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.002599999999999987.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.002599999999999987.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.002599999999999987.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.002599999999999987.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
