
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0045999999999999834.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0045999999999999834.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0045999999999999834.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0045999999999999834.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
