
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.003799999999999985.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003799999999999985.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003799999999999985.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003799999999999985.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
