
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0035999999999999964.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0035999999999999964.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0035999999999999964.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0035999999999999964.log
requirements   = OpSysAndVer == "CentOS7"

queue
