
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0036000000000000025.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0036000000000000025.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0036000000000000025.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0036000000000000025.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
