
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.004699999999999999.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004699999999999999.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004699999999999999.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004699999999999999.log
requirements   = OpSysAndVer == "CentOS7"

queue
