
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.001499999999999991.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001499999999999991.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001499999999999991.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001499999999999991.log
requirements   = OpSysAndVer == "CentOS7"

queue
