
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_1.3010426069826053e-17.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_1.3010426069826053e-17.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_1.3010426069826053e-17.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_1.3010426069826053e-17.log
requirements   = OpSysAndVer == "CentOS7"

queue
