
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0006999999999999888.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0006999999999999888.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0006999999999999888.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0006999999999999888.log
requirements   = OpSysAndVer == "CentOS7"

queue
