
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0005000000000000143.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0005000000000000143.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0005000000000000143.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0005000000000000143.log
requirements   = OpSysAndVer == "CentOS7"

queue
