
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0014000000000000167.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0014000000000000167.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0014000000000000167.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0014000000000000167.log
requirements   = OpSysAndVer == "CentOS7"

queue
