
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0006000000000000076.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0006000000000000076.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0006000000000000076.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0006000000000000076.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
