
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.001600000000000006.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001600000000000006.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001600000000000006.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.001600000000000006.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
