
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.00010000000000000048.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00010000000000000048.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00010000000000000048.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00010000000000000048.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
