
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0012999999999999904.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0012999999999999904.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0012999999999999904.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0012999999999999904.log
requirements   = OpSysAndVer == "CentOS7"

queue
