
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.00039999999999998804.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00039999999999998804.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00039999999999998804.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00039999999999998804.log
requirements   = OpSysAndVer == "CentOS7"

queue
