
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0017999999999999917.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0017999999999999917.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0017999999999999917.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0017999999999999917.log
requirements   = OpSysAndVer == "CentOS7"

queue
