
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.001100000000000016.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001100000000000016.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001100000000000016.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001100000000000016.log
requirements   = OpSysAndVer == "CentOS7"

queue
