
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.00040000000000001406.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00040000000000001406.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00040000000000001406.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00040000000000001406.log
requirements   = OpSysAndVer == "CentOS7"

queue
