
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0025000000000000196.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0025000000000000196.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0025000000000000196.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0025000000000000196.log
requirements   = OpSysAndVer == "CentOS7"

queue
