
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.001900000000000018.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001900000000000018.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001900000000000018.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001900000000000018.log
requirements   = OpSysAndVer == "CentOS7"

queue
