
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0015999999999999912.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0015999999999999912.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0015999999999999912.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0015999999999999912.log
requirements   = OpSysAndVer == "CentOS7"

queue
