
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0032999999999999956.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0032999999999999956.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0032999999999999956.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0032999999999999956.log
requirements   = OpSysAndVer == "CentOS7"

queue
