
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0010000000000000156.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0010000000000000156.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0010000000000000156.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0010000000000000156.log
requirements   = OpSysAndVer == "CentOS7"

queue
