
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0020000000000000183.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0020000000000000183.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0020000000000000183.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0020000000000000183.log
requirements   = OpSysAndVer == "CentOS7"

queue
