
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0008000000000000151.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0008000000000000151.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0008000000000000151.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0008000000000000151.log
requirements   = OpSysAndVer == "CentOS7"

queue
