
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0038999999999999972.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0038999999999999972.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0038999999999999972.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0038999999999999972.log
requirements   = OpSysAndVer == "CentOS7"

queue
