
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0007000000000000148.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0007000000000000148.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0007000000000000148.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0007000000000000148.log
requirements   = OpSysAndVer == "CentOS7"

queue
