
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.002300000000000019.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.002300000000000019.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.002300000000000019.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.002300000000000019.log
requirements   = OpSysAndVer == "CentOS7"

queue
