
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0014000000000000063.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0014000000000000063.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0014000000000000063.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0014000000000000063.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
