
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.00020000000000000833.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00020000000000000833.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00020000000000000833.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00020000000000000833.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
