
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.004000000000000002.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004000000000000002.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004000000000000002.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004000000000000002.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
