
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.00019999999999999966.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00019999999999999966.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00019999999999999966.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00019999999999999966.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
