
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0021999999999999928.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0021999999999999928.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0021999999999999928.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0021999999999999928.log
requirements   = OpSysAndVer == "CentOS7"

queue
