
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.003999999999999984.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003999999999999984.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003999999999999984.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003999999999999984.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
