
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.002299999999999993.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002299999999999993.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002299999999999993.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.002299999999999993.log
requirements   = OpSysAndVer == "CentOS7"

queue
