
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0002999999999999878.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0002999999999999878.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0002999999999999878.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0002999999999999878.log
requirements   = OpSysAndVer == "CentOS7"

queue
