
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.004299999999999998.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004299999999999998.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004299999999999998.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004299999999999998.log
requirements   = OpSysAndVer == "CentOS7"

queue
