
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0017999999999999882.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0017999999999999882.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0017999999999999882.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0017999999999999882.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
