
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0013999999999999907.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0013999999999999907.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0013999999999999907.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0013999999999999907.log
requirements   = OpSysAndVer == "CentOS7"

queue
