
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.00019999999999998751.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00019999999999998751.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00019999999999998751.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.00019999999999998751.log
requirements   = OpSysAndVer == "CentOS7"

queue
