
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0015999999999999886.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0015999999999999886.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0015999999999999886.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0015999999999999886.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
