
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0030000000000000035.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0030000000000000035.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0030000000000000035.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0030000000000000035.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
