
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.003099999999999995.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003099999999999995.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003099999999999995.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003099999999999995.log
requirements   = OpSysAndVer == "CentOS7"

queue
