
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0006000000000000146.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0006000000000000146.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0006000000000000146.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0006000000000000146.log
requirements   = OpSysAndVer == "CentOS7"

queue
