
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0004999999999999883.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0004999999999999883.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0004999999999999883.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0004999999999999883.log
requirements   = OpSysAndVer == "CentOS7"

queue
