
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0027999999999999943.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0027999999999999943.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0027999999999999943.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0027999999999999943.log
requirements   = OpSysAndVer == "CentOS7"

queue
