
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0040000000000000235.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0040000000000000235.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0040000000000000235.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0040000000000000235.log
requirements   = OpSysAndVer == "CentOS7"

queue
