
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0011999999999999901.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0011999999999999901.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0011999999999999901.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0011999999999999901.log
requirements   = OpSysAndVer == "CentOS7"

queue
