
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0024000000000000193.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0024000000000000193.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0024000000000000193.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0024000000000000193.log
requirements   = OpSysAndVer == "CentOS7"

queue
