
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.003799999999999997.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003799999999999997.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003799999999999997.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003799999999999997.log
requirements   = OpSysAndVer == "CentOS7"

queue
