
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.003399999999999996.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003399999999999996.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003399999999999996.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.003399999999999996.log
requirements   = OpSysAndVer == "CentOS7"

queue
