
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.004600000000000001.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004600000000000001.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004600000000000001.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.004600000000000001.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
