
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0018000000000000056.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0018000000000000056.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0018000000000000056.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0018000000000000056.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
