
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0036999999999999967.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0036999999999999967.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0036999999999999967.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0036999999999999967.log
requirements   = OpSysAndVer == "CentOS7"

queue
