
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0018000000000000177.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0018000000000000177.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0018000000000000177.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0018000000000000177.log
requirements   = OpSysAndVer == "CentOS7"

queue
