
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.00019999999999999098.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00019999999999999098.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00019999999999999098.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00019999999999999098.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
