
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0029000000000000215.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0029000000000000215.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0029000000000000215.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0029000000000000215.log
requirements   = OpSysAndVer == "CentOS7"

queue
