
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.00010000000000001327.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00010000000000001327.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00010000000000001327.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00010000000000001327.log
requirements   = OpSysAndVer == "CentOS7"

queue
