
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.004799999999999982.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004799999999999982.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004799999999999982.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004799999999999982.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 10Gb

queue
