
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0031999999999999954.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0031999999999999954.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0031999999999999954.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_-0.0031999999999999954.log
requirements   = OpSysAndVer == "CentOS7"

queue
