
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.00260000000000002.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00260000000000002.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00260000000000002.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.00260000000000002.log
requirements   = OpSysAndVer == "CentOS7"

queue
