
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.003400000000000022.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003400000000000022.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003400000000000022.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.003400000000000022.log
requirements   = OpSysAndVer == "CentOS7"

queue
