
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.0013000000000000164.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0013000000000000164.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0013000000000000164.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.0013000000000000164.log
requirements   = OpSysAndVer == "CentOS7"

queue
