
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.001500000000000017.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001500000000000017.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001500000000000017.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.001500000000000017.log
requirements   = OpSysAndVer == "CentOS7"

queue
