
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.004200000000000024.sh
output         = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004200000000000024.out
error          = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004200000000000024.err             
log            = /data/neutrino03/jnugent/Unfolding/MCscanrotang/rot_ang_0/LiHMu_3200_0.004200000000000024.log
requirements   = OpSysAndVer == "CentOS7"

queue
