
universe       = vanilla
executable     = LiHMu_3200_tof_lim27.4918072213_u27.6918072213.sh
output         = /data/neutrino03/jnugent/Unfolding/MCTOFsys/LiHMu_3200_tof_lim27.4918072213_u27.6918072213.out
error          = /data/neutrino03/jnugent/Unfolding/MCTOFsys/LiHMu_3200_tof_lim27.4918072213_u27.6918072213.err
log            = /data/neutrino03/jnugent/Unfolding/MCTOFsys/LiHMu_3200_tof_lim27.4918072213_u27.6918072213.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 50 GB

queue
