
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.0024999999999999935.sh
output         = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_-0.0024999999999999935.out
error          = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_-0.0024999999999999935.err             
log            = test.log
requirements   = OpSysAndVer == "CentOS7"

queue
