
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_0.006999999999999987.sh
output         = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_0.006999999999999987.out
error          = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_0.006999999999999987.err
log            = test.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 6 GB

queue
