
universe       = vanilla
executable     = rot_ang_0/LiHMu_3200_-0.003000000000000006.sh
output         = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_-0.003000000000000006.out
error          = /data/neutrino03/jnugent/Unfolding/scanrotang/rot_ang_0/LiHMu_3200_-0.003000000000000006.err
log            = test.log
requirements   = OpSysAndVer == "CentOS7"
request_memory = 6 GB

queue
